### PR TITLE
Verification Page + Nodemailer Service Setup

### LINKED ISSUE #42: Backend: Email Verification Service
See #41 

Approach:
- Use existing open source service for this
- Create a micro service for verification. In this case `services` dir can be created in root dir as all the services will be hosted separately as background workers.

### LINKED ISSUE #43: Frontend: Email Verification Page
See #41

### LINKED ISSUE #78: Backend: Nodemailer Mail Service
Create Nodemailer mail service

### PR DESCRIPTION
**Pull request by Kanav-Arora**
Closes:
- Closes #42 
- Closes #43 

Verification backend is designed in such a way that verification code can be generated for both email verification as well as password change.

Screenshot 2024-02-01 at 12 26 10 PM

Screenshot 2024-02-01 at 12 26 33 PM

WIP: Resend verification code and forgot password verification code api

### CODE REVIEW

**Comment by Aadi71** [comment]
Let's handle this error on FE, if the user already exists for email, still we get the nudge to enter OTP
image

https://congtuanle.medium.com/mongoerror-e11000-duplicate-key-error-collection-695e7e9ccdc4

**Comment by Aadi71** [comment]
image
Facing this just after I sign-up and try to click proceed

**Comment by Aadi71** [comment]
I received both emails, for verification and welcome mail. Approving it based on that, we can check out the flow once though. 
Like why I am getting the OTP prompt again if I am unable to sign-up at first. I guess state didn't change at FE.

**Review by Aadi71 — APPROVED** [review]
Great, OG work. Added some comments that can be checked and verified once. Though not blockers.

**Comment by Kanav-Arora** [comment]
@Aadi71 its working seamlessly for me but I found an issue that if user already exists he should be redirected to login page from signup but here he's been directed to verification page. I'll fix that in this PR only

**Pull request merged**
