### PR TITLE
Centered the Header

### LINKED ISSUE #98: Fix Header sections
The header is not centred properly.

Screenshot 2024-04-06 at 11 37 28 AM

### PR DESCRIPTION
**Pull request by AmirrezaAPTech**
I made changes to the style of the navigation container in the NavBar component to center the navigation links horizontally on the screen.

Closes #98

### CODE REVIEW

**Comment by Kanav-Arora** [comment]
Hi @AmirrezaAPTech 
Thanks for contributing 

Can you change it by giving first and last section as 20% and center section as 100%. Just like `LocationNavbar` you can introduce styled component just like `LocationNavbar`. We want consistency in the code so if you can please shift to styled components.

**Comment by AmirrezaAPTech** [comment]
Hi @Kanav-Arora 
I shifted Navbar just like LocationNavbar to styled components.
also I gave first section width of 20%

**Comment by Kanav-Arora** [comment]
Hi @AmirrezaAPTech 
Great will give a look to it! Thanks

**Comment by Kanav-Arora** [comment]
Hi @AmirrezaAPTech 
Great work!

**Review by Kanav-Arora — APPROVED** [review]

**Pull request merged**
